# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      git config user.email "dcfinlinson@gmail.com"
      git config user.name "Derek Finlinson"
      git remote set-url origin https://$(github.user):$(GH_TOKEN)@github.com/derekfinlinson/d365-cli.git
    displayName: 'git config'
    env: 
      GH_TOKEN: $(GH_TOKEN)
  - script: |
      yarn
    displayName: 'yarn'
  - script: |
      yarn check
    displayName: 'check change files'
  - script: |
      yarn build
    displayName: 'build'
  - script: |
      yarn beachball:publish -n $(npm.authtoken) -y
    displayName: 'beachball publish'
    env:
      NPM_TOKEN: $(NPM_TOKEN)
